# Generated by Django 4.2.1 on 2023-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Название на русском')),
                ('title_kz', models.CharField(blank=True, max_length=100, verbose_name='Название на казахском')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Название на английском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания тура')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления тура')),
                ('icon_name', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
                ('icon_collection', models.CharField(blank=True, max_length=100, verbose_name='Коллекция иконок')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
