# Generated by Django 4.2.1 on 2023-05-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('edate', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания тура')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления тура')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Туры',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created_at'],
            },
        ),
    ]
