# Generated by Django 4.2.1 on 2023-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
