# Generated by Django 4.2.1 on 2023-05-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tours_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='bdate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='edate',
        ),
    ]
