# Generated by Django 4.2.1 on 2023-05-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_regions_level_regions_lft_regions_rght_and_more'),
        ('agent', '0002_agentpublications'),
        ('tours', '0003_rename_bdate_tours_date_remove_tours_edate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Категория на русском')),
                ('title_kz', models.CharField(blank=True, max_length=100, verbose_name='Категория на казахском')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Категория на английском')),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d', verbose_name='Изображение')),
                ('icon_name', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
                ('icon_collection', models.CharField(blank=True, max_length=100, verbose_name='Коллекция иконок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания тура')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления тура')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, verbose_name='День')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Программа тура',
                'verbose_name_plural': 'Программа тура',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tours',
            name='date',
        ),
        migrations.AddField(
            model_name='tours',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.agent', verbose_name='Местность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='regions.regions', verbose_name='Местность'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TourProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, verbose_name='Время')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tour_program', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tourprogram', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Расписание тура',
                'verbose_name_plural': 'Расписание тура',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='tour',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tours', verbose_name='Тур'),
        ),
        migrations.CreateModel(
            name='TourDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата тура')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tour', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tours', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tours',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tours.tourcategory', verbose_name='Категории'),
            preserve_default=False,
        ),
    ]
