# Generated by Django 4.2.1 on 2023-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourcategory_tourprogram_remove_tours_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdates',
            options={'ordering': ['-created_at'], 'verbose_name': 'Дата тура', 'verbose_name_plural': 'Дата тура'},
        ),
        migrations.AddField(
            model_name='tourdates',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Активно'), ('2', 'Тур идет'), ('3', 'Завершен'), ('4', 'Отменен')], max_length=3),
        ),
    ]
