# Generated by Django 4.2.1 on 2023-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('tours', '0006_alter_tours_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='additional_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='tours',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='services_additional', to='services.services', verbose_name='Дополнительно оплачивается'),
        ),
        migrations.AddField(
            model_name='tours',
            name='count_days',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='count_people',
            field=models.IntegerField(blank=True, default=0, verbose_name='Максимальное количество туристов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='included_in_price',
            field=models.ManyToManyField(blank=True, related_name='services_included_in_price', to='services.services', verbose_name='Входит в стоимость'),
        ),
        migrations.AddField(
            model_name='tours',
            name='not_included_price',
            field=models.ManyToManyField(blank=True, related_name='services_not_included_in_price', to='services.services', verbose_name='Не входит в стоимость'),
        ),
        migrations.AddField(
            model_name='tours',
            name='vip',
            field=models.BooleanField(blank=True, default=1, verbose_name='VIP тур'),
            preserve_default=False,
        ),
    ]
