# Generated by Django 4.2.1 on 2023-05-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_locations_region'),
        ('tours', '0008_remove_tours_category_tours_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='locations',
            field=models.ManyToManyField(to='locations.locations', verbose_name='Локации'),
        ),
    ]
