# Generated by Django 4.2.1 on 2023-05-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Статус агента')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, upload_to='media/agent/publications/%Y/%m/%d', verbose_name='Изображение')),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent', verbose_name='Тур агент')),
            ],
            options={
                'verbose_name': 'Публикации агента',
                'verbose_name_plural': 'Публикации агента',
                'ordering': ['-created_at'],
            },
        ),
    ]
