# Generated by Django 4.2.1 on 2023-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='media/attractions/%Y/%m/%d', verbose_name='Изображение')),
                ('longitude', models.CharField(blank=True, max_length=100, verbose_name='Ширина')),
                ('latitude', models.CharField(blank=True, max_length=100, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Достопримечательности',
                'verbose_name_plural': 'Достопримечательности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Название на русском')),
                ('title_kz', models.CharField(blank=True, max_length=100, verbose_name='Название на казахском')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Название на английском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категории локаций',
                'verbose_name_plural': 'Категории локаций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('longitude', models.CharField(blank=True, max_length=100, verbose_name='Ширина')),
                ('latitude', models.CharField(blank=True, max_length=100, verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, upload_to='media/locations/%Y/%m/%d', verbose_name='Изображение')),
                ('attraction', models.ManyToManyField(blank=True, to='locations.attractions', verbose_name='Достопримечательности')),
                ('category', models.ManyToManyField(blank=True, to='locations.locationcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Локации',
                'verbose_name_plural': 'Локации',
                'ordering': ['-created_at'],
            },
        ),
    ]
