# Generated by Django 4.2.1 on 2023-05-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_regions_image'),
        ('locations', '0002_alter_locations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='region',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='regions.regions', verbose_name='Регион'),
            preserve_default=False,
        ),
    ]
