# Generated by Django 4.2.1 on 2023-05-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_locations_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Приоритетная'),
        ),
    ]
