# Generated by Django 4.2.1 on 2023-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locations_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание'),
        ),
    ]
