# Generated by Django 4.2.1 on 2023-05-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('tour', 'Тур'), ('attraction', 'Достопримечательности'), ('location', 'Локации')], max_length=10)),
                ('item_id', models.IntegerField(verbose_name='ID материала')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/uploads/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Дополнительные изображения',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
